concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "my-runner"
  url = "http://leading_engineering_schools-web-1"
  id = 2
  token = "dxV3S5Jk8EwdCadvWaS9"
  token_obtained_at = 2023-10-27T14:46:55Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab-runner register \\"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://leading_engineering_schools-web-1"
  id = 3
  token = "YeJJSnChnRk1RzdPJAaz"
  token_obtained_at = 2023-10-27T14:55:36Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://leading_engineering_schools-web-1"
  id = 4
  token = "hnxYwLbsmiw89TG1MDkv"
  token_obtained_at = 2023-10-27T15:10:27Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 5
  token = "NranyrRt3kumXhBPsQ5W"
  token_obtained_at = 2023-10-27T15:20:50Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 6
  token = "Z4CZqK7KtoJx4zMgZogr"
  token_obtained_at = 2023-10-27T15:48:46Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 7
  token = "KsbjpGAsV4SDQUQMU5Qu"
  token_obtained_at = 2023-10-27T16:59:02Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 8
  token = "8yx2yFSy7wkF7_aNZpy_"
  token_obtained_at = 2023-10-27T19:48:09Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 9
  token = "P2DJD7YxKtJyd2hZvEWK"
  token_obtained_at = 2023-10-27T20:37:20Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 10
  token = "Zp97uCkHys7SKpq9MnrG"
  token_obtained_at = 2023-10-27T21:18:57Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "my-runner"
  url = "http://172.17.0.1"
  id = 11
  token = "1_JNUsqZJttku3k8bQq-"
  token_obtained_at = 2023-10-27T21:32:25Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "gitlab/gitlab-ce:latest"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
